Method,Name,Error,Occurrences
GET,/api/store-events-producer-fn?count=8,502 Server Error: Bad Gateway for url: https://latency-store-front-us-apim-004.azure-api.net/api/store-events-producer-fn?count=8,1
GET,/api/store-events-producer-fn?count=7,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=7 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d453dde40>: Failed to establish a new connection: [Errno 11] Resource temporarily unavailable'))",13
GET,/api/store-events-producer-fn?count=3,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d45832aa0>: Failed to establish a new connection: [Errno 11] Resource temporarily unavailable'))",10
GET,/api/store-events-producer-fn?count=4,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d4d9abc40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",3
GET,/api/store-events-producer-fn?count=6,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=6 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d4964f0a0>: Failed to establish a new connection: [Errno 11] Resource temporarily unavailable'))",17
GET,/api/store-events-producer-fn?count=9,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=9 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d7d43d4b0>: Failed to establish a new connection: [Errno 24] Too many open files'))",73303
GET,/api/store-events-producer-fn?count=7,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=7 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d44771f30>: Failed to establish a new connection: [Errno 0] Error'))",1
GET,/api/store-events-producer-fn?count=1,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d451aeda0>: Failed to establish a new connection: [Errno 11] Resource temporarily unavailable'))",13
GET,/api/store-events-producer-fn?count=5,502 Server Error: Bad Gateway for url: https://latency-store-front-us-apim-004.azure-api.net/api/store-events-producer-fn?count=5,1
GET,/api/store-events-producer-fn?count=3,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d492ff250>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",2
GET,/api/store-events-producer-fn?count=9,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=9 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d45e93eb0>: Failed to establish a new connection: [Errno 11] Resource temporarily unavailable'))",11
GET,/api/store-events-producer-fn?count=10,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=10 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d7d599ae0>: Failed to establish a new connection: [Errno 24] Too many open files'))",73399
GET,/api/store-events-producer-fn?count=1,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=1 (Caused by SSLError(OSError(24, 'Too many open files')))",43
GET,/api/store-events-producer-fn?count=8,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=8 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d48176500>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",3
GET,/api/store-events-producer-fn?count=9,502 Server Error: Bad Gateway for url: https://latency-store-front-us-apim-004.azure-api.net/api/store-events-producer-fn?count=9,2
GET,/api/store-events-producer-fn?count=4,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=4 (Caused by SSLError(OSError(24, 'Too many open files')))",27
GET,/api/store-events-producer-fn?count=7,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=7 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d7d59ae30>: Failed to establish a new connection: [Errno 24] Too many open files'))",73525
GET,/api/store-events-producer-fn?count=8,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=8 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d4d6c2440>: Failed to establish a new connection: [Errno 11] Resource temporarily unavailable'))",11
GET,/api/store-events-producer-fn?count=8,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=8 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d7d598070>: Failed to establish a new connection: [Errno 24] Too many open files'))",73499
GET,/api/store-events-producer-fn?count=4,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d540ea4d0>: Failed to establish a new connection: [Errno 11] Resource temporarily unavailable'))",12
GET,/api/store-events-producer-fn?count=3,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=3 (Caused by SSLError(OSError(24, 'Too many open files')))",27
GET,/api/store-events-producer-fn?count=9,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=9 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d4e639960>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",8
GET,/api/store-events-producer-fn?count=4,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d7d5c0190>: Failed to establish a new connection: [Errno 24] Too many open files'))",73296
GET,/api/store-events-producer-fn?count=6,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=6 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d46e61d20>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",5
GET,/api/store-events-producer-fn?count=5,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=5 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d45c94430>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",6
GET,/api/store-events-producer-fn?count=9,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=9 (Caused by SSLError(OSError(24, 'Too many open files')))",33
GET,/api/store-events-producer-fn?count=7,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=7 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d45e921a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",4
GET,/api/store-events-producer-fn?count=7,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=7 (Caused by SSLError(OSError(24, 'Too many open files')))",25
GET,/api/store-events-producer-fn?count=10,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=10 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d45aab0d0>: Failed to establish a new connection: [Errno 11] Resource temporarily unavailable'))",17
GET,/api/store-events-producer-fn?count=1,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d7d464400>: Failed to establish a new connection: [Errno 24] Too many open files'))",73416
GET,/api/store-events-producer-fn?count=6,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=6 (Caused by SSLError(OSError(24, 'Too many open files')))",30
GET,/api/store-events-producer-fn?count=2,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d5682ee90>: Failed to establish a new connection: [Errno 11] Resource temporarily unavailable'))",20
GET,/api/store-events-producer-fn?count=1,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d4ea1c910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",3
GET,/api/store-events-producer-fn?count=1,502 Server Error: Bad Gateway for url: https://latency-store-front-us-apim-004.azure-api.net/api/store-events-producer-fn?count=1,2
GET,/api/store-events-producer-fn?count=10,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=10 (Caused by SSLError(OSError(24, 'Too many open files')))",41
GET,/api/store-events-producer-fn?count=5,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=5 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d459d2650>: Failed to establish a new connection: [Errno 11] Resource temporarily unavailable'))",15
GET,/api/store-events-producer-fn?count=10,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=10 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d4a335660>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",6
GET,/api/store-events-producer-fn?count=7,502 Server Error: Bad Gateway for url: https://latency-store-front-us-apim-004.azure-api.net/api/store-events-producer-fn?count=7,2
GET,/api/store-events-producer-fn?count=6,502 Server Error: Bad Gateway for url: https://latency-store-front-us-apim-004.azure-api.net/api/store-events-producer-fn?count=6,1
GET,/api/store-events-producer-fn?count=2,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=2 (Caused by SSLError(OSError(24, 'Too many open files')))",32
GET,/api/store-events-producer-fn?count=2,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d459d0f10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",7
GET,/api/store-events-producer-fn?count=8,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=8 (Caused by SSLError(OSError(24, 'Too many open files')))",30
GET,/api/store-events-producer-fn?count=2,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d7d5f5cc0>: Failed to establish a new connection: [Errno 24] Too many open files'))",73216
GET,/api/store-events-producer-fn?count=6,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=6 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d7d5c1330>: Failed to establish a new connection: [Errno 24] Too many open files'))",73218
GET,/api/store-events-producer-fn?count=3,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d7d5770d0>: Failed to establish a new connection: [Errno 24] Too many open files'))",72965
GET,/api/store-events-producer-fn?count=5,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=5 (Caused by SSLError(OSError(24, 'Too many open files')))",37
GET,/api/store-events-producer-fn?count=3,502 Server Error: Bad Gateway for url: https://latency-store-front-us-apim-004.azure-api.net/api/store-events-producer-fn?count=3,1
GET,/api/store-events-producer-fn?count=5,"HTTPSConnectionPool(host='latency-store-front-us-apim-004.azure-api.net', port=443): Max retries exceeded with url: /api/store-events-producer-fn?count=5 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d7d5f4520>: Failed to establish a new connection: [Errno 24] Too many open files'))",73204
